spring:
  datasource:
    url: jdbc:mysql://
    username:
    password:
  jpa:
    show-sql: true
  redis:
    host:
    password:
    client-type: lettuce
eureka:
  client:
    serviceUrl:
      defaultZone: http://0.0.0.0:0000/eureka