spring:
  datasource:
    url: jdbc:mysql://0.0.0.0:3306/ouo
    username: root
    password: 0
  jpa:
    show-sql: true
  cloud:
    nacos:
      discovery:
        server-addr: 0.0.0.0:0
        namespace: ouo-prod
  data:
    redis:
      host: 0.0.0.0
      password: 0
      client-type: lettuce