spring:
  datasource:
    url: jdbc:mysql://0.0.0.0:3306/ouo
    username: root
    password: 0
  jpa:
    show-sql: true
  redis:
    host: 0.0.0.0
    password: 0
    client-type: lettuce
eureka:
  client:
    serviceUrl:
      defaultZone: http://0.0.0.0:0/eureka