server:
  port: 0
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 0.0.0.0:0
        namespace:
    gateway:
      routes:
      - id: auth
        uri: lb://auth
        predicates:
        - Path=/auth/**
        filters:
        - StripPrefix=1
logging:
  file:
    name: gateway.log