server:
  port:
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
      - id: auth
        uri: lb://auth
        predicates:
        - Path=/auth/**
        filters:
        - StripPrefix=1
eureka:
  client:
    serviceUrl:
      defaultZone: http://0.0.0.0:0000/eureka
logging:
  file:
    name: /../gateway.log

