server:
  port: 0
spring:
  application:
    name: eureka-server
eureka:
  client:
    serviceUrl:
      defaultZone: http://0.0.0.0:${server.port}/eureka
    register-with-eureka: false
    fetch-registry: false
logging:
  file:
    name: /.../eureka-server.log