server:
  port:
spring:
  application:
    name: eureka-server
eureka:
  client:
    serviceUrl:
      defaultZone: http://0.0.0.0:0000/eureka
    register-with-eureka: false
logging:
  file:
    name: /.../eureka-server.log
